[package]
name = "kuvpn"
version = "0.6.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
headless_chrome = { version = "1.0.14", features = ["fetch", "rustls"] }

[profile.release]
strip = true
lto = true
codegen-units = 1