[package]
name = "kuvpn"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
fantoccini = { version = "0.21.0", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["tokio-macros", "rt", "macros", "rt-multi-thread", "process"] }
