[package]
name = "kuvpn"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.21.0"
tokio = { version = "1.39.2", features = ["tokio-macros", "rt", "macros", "rt-multi-thread", "process"] }
