name: Mac x64 Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: openssl pkg-config
          
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          cache: true

      - name: Build CLI
        run: |
          cargo build --release -p kuvpn

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: kuvpn-x86_64-apple-darwin
          path: |
            ./target/release/kuvpn
